substitutions:
  _IMAGE_NAME: 'gcr.io/${PROJECT_ID}/candy-shop:${SHORT_SHA}'

steps:

  # Build docker image 
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_IMAGE_NAME', '.']

images:
  - $_IMAGE_NAME

options:
  logging: CLOUD_LOGGING_ONLY
