substitutions:
  _TAG: '$SHORT_SHA'
  _IMAGE_NAME: gcr.io/$PROJECT_ID/$candyShop:$_TAG

steps:

  # Build docker image 
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_IMAGE_NAME', '.']


options:
  logging: CLOUD_LOGGING_ONLY
